Use either DATABASE_URL or ind. parameters in 70_initdb

diff --git a/etc/my_init.d/70_initdb b/etc/my_init.d/70_initdb
--- a/etc/my_init.d/70_initdb
+++ b/etc/my_init.d/70_initdb
@@ -2,7 +2,11 @@
 set -eu
 
 #A tiger table interferes with a CKAN table, and we don't need tiger anyway
-psql "postgresql://${DB_ENV_POSTGRES_USER}:${DB_ENV_POSTGRES_PASS}@${DB_PORT_5432_TCP_ADDR}:${DB_PORT_5432_TCP_PORT}/${DB_ENV_POSTGRES_DB}" -c "drop extension postgis_tiger_geocoder" || echo "Command failed; probably not a problem";
+: ${DATABASE_URL:=}
+if [ -z "$DATABASE_URL" ]; then
+    DATABASE_URL="postgresql://${DB_ENV_POSTGRES_USER}:${DB_ENV_POSTGRES_PASS}@${DB_PORT_5432_TCP_ADDR}:${DB_PORT_5432_TCP_PORT}/${DB_ENV_POSTGRES_DB}"
+fi
+psql $DATABASE_URL -c "drop extension postgis_tiger_geocoder" || echo "Command failed; probably not a problem";
 
 "$CKAN_HOME"/bin/paster --plugin=ckan db init -c "${CKAN_CONFIG}/ckan.ini"
-"$CKAN_HOME"/bin/paster --plugin=ckan datastore set-permissions -c "${CKAN_CONFIG}/ckan.ini" | psql "${DATASTORE_DB_URL}"
+"$CKAN_HOME"/bin/paster --plugin=ckan datastore set-permissions -c "${CKAN_CONFIG}/ckan.ini" | psql $DATASTORE_DB_URL
